### ISSUE TITLE
Can't register my phone number

### ISSUE THREAD

**Issue by santote** [vysheng/tg#440]
Hi, i'm installing Telegram Cli on my raspberry pi to send the state of some GPIO pins.
When I try to enter in first time with "bin/telegram-cli -k tg-server.pub -W", i don't receive the lines to configure my phone number. I onl see this:

pi@raspberrypi ~/tg $ bin/telegram-cli -k /var/lib/pi/tg/tg-server.pub
Telegram-cli version 1.2.0, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 1.2.0
I: config dir=[/home/pi/.telegram-cli]
>

Thank you very much.

**Comment by majn** [comment]
I've noticed this in telegram-purple too. There's a problem during authentication since an IP of the telegram data center has changed and the login somehow seems to depend on the hard-coded presets. According to the log the discovery returns these data center addresses:

    15:03:32: (Libpurple: prpl-telegram) DC1 '' update: 149.154.175.50:443
    15:03:32: (Libpurple: prpl-telegram) DC2 '' update: 149.154.167.51:443
    15:03:32: (Libpurple: prpl-telegram) DC3 '' update: 149.154.175.100:443
    15:03:32: (Libpurple: prpl-telegram) DC4 '' update: 149.154.167.91:443
    15:03:32: (Libpurple: prpl-telegram) DC5 '' update: 149.154.171.5:443

In tgl.h you will see:

   #define TG_SERVER_1 "149.154.175.50"
   #define TG_SERVER_2 "149.154.167.51"
   #define TG_SERVER_3 "174.140.142.6"
   #define TG_SERVER_4 "149.154.167.91"
   #define TG_SERVER_5 "149.154.171.5"

Change the third entry in tgl.h to 

      #define TG_SERVER_3 "149.154.175.100"

and it will work again. I've submitted a pull request:  https://github.com/vysheng/tg/issues/440

Of course this is just a hotfix, there is probably some bigger issue in the code that has to be fixed, the data center discovery should theoretically work and not depend on hard-coded addresses.

**Comment by santote** [comment]
Thanks majn for you reply, but it's still without apearing any message to input the phone number.

**Comment by majn** [comment]
Have you recompiled tg?

**Comment by majn** [comment]
Also make sure that you clear all state files in ~/.telegram-cli/

**Comment by santote** [comment]
Thank you very much majn, i didn't know how to recompile tg only, i recompiled all with make command.
It worked perfect.
Thanks a lot.

**Comment by reekoheek** [comment]
I think this issue resolved by hot fix from majn

**Comment by AndydeCleyre** [comment]
@majn's fix saved me as well. Thanks @majn!

**Comment by Maverick-GH** [comment]
Hi @majn ,

When you say "make sure that you clear all state files in ~/.telegram-cli/", you mean the only one "state" file, right ? Are there any other files that I should clear ?
Thanks in advance

**Comment by majn** [comment]
@Maverick-GH  No, actually I meant to clear all the files not only the state file.

**Comment by Maverick-GH** [comment]
@majn , I removed every single file/diretory from .telegram-cli and tried to run bin/telegram-cli -k tg-server.pub again. Same problem. Still hangs...
Should I try ./configure again ? Or is there anything else I could do ?
Thanks

**Comment by VengadoraVG** [comment]
I downloaded telegram-cli yesterday, it comes with the new line:

  #define TG_SERVER_3 "149.154.175.100"

anyway, I still have the same problem :( maybe an IP of the telegram's data center changed again?

**Comment by khaledelcheikh** [comment]
Hello guys, any updates regarding the issue? I have downloaded the repo today and still facing the issue. no phone number required and i couldn't ping any of the IPs found in the tgl.h

#define TG_SERVER_1 "149.154.175.50"
#define TG_SERVER_2 "149.154.167.51"
#define TG_SERVER_3 "149.154.175.100"
#define TG_SERVER_4 "149.154.167.91"
#define TG_SERVER_5 "149.154.171.5"

root@ubuntu:/tg# bin/telegram-cli -k tg-server.pub
change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.2
Telegram-cli uses libpython version 2.7.6
I: config dir=[/home/khaled/.telegram-cli]
>

Please help and thanks in advance!

**Comment by LukeLR** [comment]
Ping works fine for me on all the IPs. therefore it seems to be an issue related to your network connection. Are you behind a firewall or proxy server?

**Comment by khaledelcheikh** [comment]
Hi, it worked after granting direct internet access.

Thanks a lot for your quick reply.

**Comment by LukeLR** [comment]
You're welcome :)

**Comment by Maverick-GH** [comment]
In my case, it was a network configuration issue. The server couldn't reach internet in order to accomplish configuration.
    So, since you can't reach any of those IPs, I guess you have the same problem.

Em 16/06/2015 09:51, khaledelcheikh <notifications@github.com> escreveu:
Hello guys, any updates regarding the issue? I have downloaded the repo today and still facing the issue. no phone number required and i couldn't ping any of the IPs found in the tgl.h

#define TG_SERVER_1 "149.154.175.50"
#define TG_SERVER_2 "149.154.167.51"
#define TG_SERVER_3 "149.154.175.100"
#define TG_SERVER_4 "149.154.167.91"
#define TG_SERVER_5 "149.154.171.5"

root@ubuntu:/tg# bin/telegram-cli -k tg-server.pub
change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.2
Telegram-cli uses libpython version 2.7.6
I: config dir=[/home/khaled/.telegram-cli]
>

Please help and thanks in advance!

---

**Comment by everhopingandwaiting** [comment]
./telegram-cli -k ../tg-server.pub  -v 3  -W 
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.2
Telegram-cli uses libpython version 2.7.9
I: config dir=[/home/pi/.telegram-cli]
> telegram-cli: tgl/mtproto-client.c:1242: tc_becomes_ready: Assertion `0' failed.
SIGNAL received
pi@raspberrypi ~/360upan/tools/telegram/tg/bin $ 
   ###############################################################
 also  my  IP  is   right ,  but  it  still   have  probelm!

**Comment by authorized13** [comment]
Love this concept encrypted Telegraph is the s***

**Comment by Chukwuokike** [comment]
Hello am having difficulties registering in telegram please I need help
